### ISSUE TITLE
Screen is not a constructor

### ISSUE THREAD

**Issue by jeandarcc** [node-3d/node-3d#1]
const screen = new Screen();
               ^

TypeError: Screen is not a constructor
    at Object.<anonymous> (C:\Users\User\3dproject\index.js:5:16)
[90m    at Module._compile (internal/modules/cjs/loader.js:959:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:815:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:727:14)[39m
[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)[39m
[90m    at internal/main/run_main_module.js:17:11[39m

**Comment by raub** [comment]
Hello!

Any steps to reproduce that? What is `Screen` in this context anyway?

Did it come from the code like this?
```
const init = require('3d-core-raub');
const { Screen, loop } = init();

const screen = new Screen();
loop(() => screen.draw());
```

**Comment by JSDevloop** [comment]
> Hello!
> 
> Any steps to reproduce that? What is `Screen` in this context anyway?
> 
> Did it come from the code like this?
> 
> ```
> const init = require('3d-core-raub');
> const { Screen, loop } = init();
> 
> const screen = new Screen();
> loop(() => screen.draw());
> ```

Yes i've tried this code.

**Comment by jeandarcc** [comment]
> Hello!
> 
> Any steps to reproduce that? What is `Screen` in this context anyway?
> 
> Did it come from the code like this?
> 
> ```
> const init = require('3d-core-raub');
> const { Screen, loop } = init();
> 
> const screen = new Screen();
> loop(() => screen.draw());
> ```

I solved the problem. 
```
const init = require('3d-core-raub');
const { Screen, loop } = init();
```
This is working.

`const { Screen, loop } = require('3d-core-raub');`
This is not working.
