### ISSUE TITLE
Can't initialize GLEW

### ISSUE THREAD

**Issue by bushyice** [node-3d/node-3d#5]
Hello, anything i run(that requires `3d-core-raub`)  ends up with this error:
```
Error: Unknown error
/home/makano/workspace/3d-core-raub/node_modules/glfw-raub/js/document.js:28
				Document.webgl.init();
				              ^

Error: Can't initialize GLEW.
    at new Document (/home/makano/workspace/3d-core-raub/node_modules/glfw-raub/js/document.js:28:20)
    at _init (/home/makano/workspace/3d-core-raub/js/index.js:77:14)
    at init (/home/makano/workspace/3d-core-raub/js/index.js:135:11)
    at Object.<anonymous> (/home/makano/workspace/3d-core-raub/examples/3d-core/lines.js:7:37)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49

Node.js v20.12.2
```

I was trying the examples from [3d-core-raub](https://github.com/node-3d/3d-core-raub) but it keeps showing me this error.

I am using nixos with wayland, and i am using flakes for the environment:
```nix
# flake.nix
{
  inputs = {
    utils.url = "github:numtide/flake-utils";
  };
  outputs = { self, nixpkgs, utils }: utils.lib.eachDefaultSystem (system:
    let
      pkgs = (import nixpkgs {
        inherit system;
        config = {
          allowInsecure = true;
          permittedInsecurePackages = [
            "freeimage-unstable-2021-11-01"
          ];
        };
      });
      libraries = with pkgs; [
        mesa
        libGL
        libGLU
        glew
        glfw
        pkg-config
        xorg.libX11
        freeimage
      ];
    in
    {
      devShell = pkgs.mkShell {
        buildInputs = libraries;
        
        shellHook = ''
          export LD_LIBRARY_PATH=${pkgs.lib.makeLibraryPath libraries}:$LD_LIBRARY_PATH
        '';
      };
    }
  );
}
```

Here's the `$LD_LIBRARY_PATH`:
```
/nix/store/dzxwp1wpv8chbv9df1vw1jfpaix9mgjr-mesa-24.1.1/lib:/nix/store/a5vcvrkh1c2ng5kr584g3zw3991vnhks-libGL-1.7.0/lib:/nix/store/i84nkq7hymsyrxy79sql6jldg9d9p4h6-glu-9.0.3/lib:/nix/store/ad6j71llskgscfyiywxwdsxh9i3z2j5p-glew-2.2.0/lib:/nix/store/2zkp24p09zvh6vkn0qxxmyqmyiibykdi-glfw-3.4/lib:/nix/store/2hfzaqv42iwrpk3ya24cnjsklz6f68lw-pkg-config-wrapper-0.29.2/lib:/nix/store/9hly244f95f2zmnr0mwsqingpyyr5yjp-libX11-1.8.9/lib:/nix/store/kcr5zrp14xbj3mcq2rn7a6skf1ypq3s0-freeimage-unstable-2021-11-01/lib:/nix/store/bn7pnigb0f8874m6riiw6dngsmdyic1g-gcc-13.3.0-lib/lib
```

By the way it works on xorg

**Comment by bushyice** [comment]
Hey, so i found out from [here](https://gitlab.kitware.com/vtk/vtk/-/issues/19357). 
As the comments say
> "_The true issue is in GLEW, but it's not going to be fixed anytime soon. In fact a upstream "fix" will probably never arrive. Even if a new release will be made, the upstream decided to "fix" the problem by adding a new API rather than fixing the broken existing one._"

From the gitlab comment i found, i think ignoring the error as this example:
```cpp
if (glewInit() != GLEW_OK) {
    std::cerr << "Failed to initialize GLEW" << std::endl;
    glfwDestroyWindow(window);
    glfwTerminate();
    return -1;
}
```
This is how you would initiate glew normally, but i think we can ignore the error like:
```cpp
if (glewInit() != GLEW_OK) {
    std::cerr << "Failed to initialize GLEW" << std::endl;
}
```

You can do this in the binary for the `glfw-raub`, don't you think?

**Comment by raub** [comment]
Hello! Yes, I think we can only fix it by ignoring, if at all.

Can you try wrapping `/home/makano/workspace/3d-core-raub/node_modules/glfw-raub/js/document.js:28` into a try-catch? If it fixes the issue, I can update the package.

**Comment by bushyice** [comment]
Yes it does work when i wrap it in a try-catch

**Comment by raub** [comment]
Hey @kevinJ045, I've published `glfw-raub` version [5.6.0](https://github.com/node-3d/glfw-raub/releases/tag/5.6.0) with the fix. Please let me know if the issue has been resolved.

**Comment by bushyice** [comment]
Yep it works, but it'd be great if you could add an option to disable warnings... ?

**Comment by raub** [comment]
In my opinion the warning is quite valid and should only happen once at launch. If your use case is very output-sensitive, maybe it would be more reasonable to patch in on your side? E.g. patch `console.warn` or `webgl.init` before it is called. In terms of client code, these solutions seem no worse than adding a whole new option.

**Comment by bushyice** [comment]
Yeah it's quite valid, but you're taking options right above it anyways, so you can make an option called logLevel or something...?

**Comment by raub** [comment]
I sure can. But that's a separate issue altogether:
- add the option
- respect the option in all places where there are logs
- update type declarations

and all of that will be specific for the `glfw-raub` module in our case. any other module will continue logging as before.

Another approach would be to create some kind of a common log layer for ALL the modules that are in this project (basically, add `logger` to `addon-tools-raub`).

Either way, the scope of such changes are too wide for this issue. I think the latter approach will be more productive, so I will create an issue to track it.

And for now, as a workaround, you can just patch the `webgl.init = () => undefined;` - it will make no difference for your project except the warning, as you already don't expect this method to work.

**Comment by bushyice** [comment]
You're right. I guess we should close this issue here then.
